spring:
  application:
    name: spring-cloud-eureka-guapmodule
server:
  port: 8070
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true