version: "3"
services:
  guap:
    image: schedapp/suai:latest
    restart: on-failure
    environment:
      - SPRING_APPLICATION_NAME=guap
      - WAIT_HOSTS=mysql:3307
      - WAIT_HOSTS_TIMEOUT=500
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    networks:
      - eureka_network
      - common_network
    ports:
      - "8070:8070"

networks:
  common_network:
    name: common_network
    external: true
  eureka_network:
    name: eureka_network
    external: true
